SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE Food;

TRUNCATE TABLE Entertainment;

TRUNCATE TABLE Venue;

TRUNCATE TABLE Date_time;

TRUNCATE TABLE Date_preferences;

TRUNCATE TABLE Date_liked;

TRUNCATE TABLE Date_disliked;

TRUNCATE TABLE Suggested_dates;

TRUNCATE TABLE Date_ideas;

TRUNCATE TABLE Connection_requests;

TRUNCATE TABLE User_security_questions;

TRUNCATE TABLE Users;

SET FOREIGN_KEY_CHECKS=1;