DROP TABLE IF EXISTS Food;

DROP TABLE IF EXISTS Entertainment;

DROP TABLE IF EXISTS Venue;

DROP TABLE IF EXISTS Date_time;

DROP TABLE IF EXISTS Date_preferences;

DROP TABLE IF EXISTS Date_liked;

DROP TABLE IF EXISTS Date_disliked;

DROP TABLE IF EXISTS Date_ideas;

DROP TABLE IF EXISTS Suggested_dates;

DROP TABLE IF EXISTS Connection_requests;

DROP TABLE IF EXISTS Users;
